name: first workflow demo
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "hello world"
      - name: print job done 
        run: echo "Bye Bye..job done!"
    
      
    
  
  
  

    
  
    
